### ISSUE TITLE
Big TimeFrame Issue

### ISSUE THREAD

**Issue by lovetrading10** [korygill/technical-analysis#2]
Hi, Kargil.
I am very interested in your project.
So I am going to do everything with your source.
By the way, I have one issue.
Can you help me?
My script doesn't run on the Big Timeframes
For example 5y 1w.
Would you please solve this issue?
I am sure that you can fix this issue quickly.
I will wait for your favorable reply.
Best regards!

**Comment by korygill** [comment]
The latest version of the scripts should allow any timeframe.
