### ISSUE TITLE
Help - tinkScript

### ISSUE THREAD

**Issue by bamideleAli** [korygill/technical-analysis#3]
Kory,
I need a little bit of hand holding here if you can spare me some of your wisdom.   One I'm not great with this site so sorry if I've put this comment/question under the wrong section but I wasn't sure how else to reach you.  I've run the thinkorSwim shared script to pull data.   I tried parse data using a CSV file app but the resultant data did not give me OHLC info.  I then tried PowerShell in the exported CSV file which is where I'm stuck.  I'm on a MAC.  I cut and paste the PowerShell Script you provided in to a data editor and saved it as a *.PS1 file (which is still showing up as an *.ps1.rtf file for some reason - I'll figure that out).  But the terminal window doesn't understand the command when i try to run your script (cmd given:  $data = .\Get-OHLC.ps1 .\StrategyReports_MU_82620.csv ) (result:  command not found).  I have everything in the same folder but i cannot seem to get your script to run to parse the data in to the needed columns of info.  Can you give me some guidance here?  Thank you.

**Comment by bamideleAli** [comment]
Oh and btw i'm much better at email:  bamidele22@me.com

**Comment by korygill** [comment]
Hello. I am unsure how to  make this work on a mac.
